Vagrant::Config.run do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "base"
  config.vm.box_url = "http://files.vagrantup.com/lucid32.box"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  # config.vm.box_url = "http://files.vagrantup.com/lucid32.box"

  # Assign this VM to a host only network IP, allowing you to access it
  # via the IP.
  config.vm.network "33.33.33.10"

  # Forward a port from the guest to the host, which allows for outside
  # computers to access the VM, whereas host only networking does not.
  # config.vm.forward_port "http", 80, 8080

  # Share an additional folder to the guest VM. The first argument is
  # an identifier, the second is the path on the guest to mount the
  # folder, and the third is the path on the host to the actual folder.
  # config.vm.share_folder "v-data", "/vagrant_data", "../data"
  
  config.vm.customize do |vm|
    vm.memory_size = 256
  end

  
  config.vm.share_folder("v-root", "/var/www/nginx-drupal", "../public_html")
  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "cookbooks"
    chef.add_recipe("apt")
    chef.add_recipe("build-essential")
    chef.add_recipe("openssl")
    chef.add_recipe("git")
    chef.add_recipe("mysql::server")
    chef.add_recipe("imagemagick")
    chef.add_recipe("php")
    chef.add_recipe("php::module_mysql")
    chef.add_recipe("php::module_gd")
    chef.add_recipe("php-fpm")
    chef.add_recipe("drush")
    chef.add_recipe("nginx")
    chef.json = { 
      :"mysql" => { :server_root_password => "root", :bind_address => "0.0.0.0" },
      :"nginx" => { :default_site_root => "/var/www/nginx-drupal", :user => "vagrant" },
      :"php-fpm" => { :user => "vagrant", :group => "vagrant"  }
    }
  end

end
